---
# This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  sudo: yes
  roles:
    - sysctl

- hosts: cluster-nodes
  roles:
    - docker
  post_tasks:
    - shell: echo 'goodbye'