---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: all
  sudo: yes
  vars_files:
    - vars/defaults.yml
  roles:
    - sysctl
    - users
    - ssh
    - franklinkim.sudo

- hosts: cluster-nodes
  post_tasks:
    - shell: echo 'goodbye'

#- hosts: coreos
#  gather_facts: False
#  roles:
#    - defunctzombie.coreos-bootstrap
