---
- name: Set up groups
  group: name={{ item.name }} state=present
  with_items: groups_params

- name: Set up users
  user: name={{ item.name }} group={{ item.group }} state=present shell={{ item.shell | default('/bin/bash') }}
  with_items: users_params
