---
# ---------------------------
# Kernel-level settings layer via sysctl
# ---------------------------
# This file needs to be present in /etc/sysctl.d
# NOTE that all features present in this config file
# are not necessarily suitable to all kinds of servers,
# you will need to set some flags on/off depending on the
# server role.

# Example use:
# sysctl_kernel_params:
#   - { name: net.ipv4.ip_forward: 1 }
#   - { name: fs.file-max, value: 65535 }
- name: 'Kernel-level settings layer via sysctl'
  sysctl: name={{ item.name }} value={{ item.value }} state=present ignoreerrors=yes
  with_items: sysctl_kernel_params
