---
# ---------------------------
# Essential packages
# ---------------------------
# This role makes sure the minimum
# necessary packages are installed

- name: Set /etc/issue.net
  copy: src=issue.net dest=/etc/issue.net mode=644 owner=root

- name: Set up essential packages (APT)
  apt: pkg={{ item }} state=installed
  with_flattened:
    - packages_base
    - packages_ubuntu
  when: ansible_pkg_mgr == 'apt'

- name: Set up essential packages (YUM)
  yum: name={{ item }} state=latest
  with_flattened:
    - packages_base
    - packages_centos
  when: ansible_pkg_mgr == 'yum'

